In [30]:
import numpy as np

a = np.array([1, 2, 3,4])

In [31]:
print(a)


[1 2 3 4]


In [32]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()

c = np.dot(a,b)

toc = time.time()

print(c)
print("Vectorized version:"+str(1000*(toc - tic))+" ms")


c = 0 

tic = time.time()

for i in range(1000000):
    c += a[i]*b[i]
    
toc = time.time()
print(c)
print("For loop version:"+str(1000*(toc - tic))+" ms")


250059.4856455082
Vectorized version:1.2791156768798828 ms
250059.48564551305
For loop version:472.93686866760254 ms


# Broadcasting

In [33]:
A = np.array([[56, 0, 23, 16],
             [213, 234, 16, 19], 
             [12, 123, 231, 54]])

print(A)

[[ 56   0  23  16]
 [213 234  16  19]
 [ 12 123 231  54]]


In [34]:
cal = A.sum(axis=0)
print(cal)
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[281 357 270  89]
[[19.92882562  0.          8.51851852 17.97752809]
 [75.80071174 65.54621849  5.92592593 21.34831461]
 [ 4.27046263 34.45378151 85.55555556 60.6741573 ]]


# A Simple Note on Numpy

In [35]:
import numpy as np

a = np.random.rand(5)
print(a)
print(a.T)
print(a.shape)

b = np.dot(a, a.T)
print(b)
c = np.dot(a, a)
print(c)

# Use this instead to be more specific

v = np.random.rand(5, 1)
print(v)
print(v.T)
print(v + v.T)

[0.69460196 0.74499365 0.79375358 0.18471074 0.35835508]
[0.69460196 0.74499365 0.79375358 0.18471074 0.35835508]
(5,)
1.83006857952227
1.83006857952227
[[0.12661264]
 [0.05987095]
 [0.99068601]
 [0.35892121]
 [0.78290647]]
[[0.12661264 0.05987095 0.99068601 0.35892121 0.78290647]]
[[0.25322527 0.18648359 1.11729864 0.48553385 0.90951911]
 [0.18648359 0.1197419  1.05055696 0.41879217 0.84277743]
 [1.11729864 1.05055696 1.98137202 1.34960722 1.77359248]
 [0.48553385 0.41879217 1.34960722 0.71784243 1.14182769]
 [0.90951911 0.84277743 1.77359248 1.14182769 1.56581295]]


In [36]:
A = np.array([[1], [2], [3]])
print(A.shape)

print(A + A.T)

(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [6]:
import numpy as np

a = np.random.randn(2, 3)
b = np.random.randn(2, 1)

c = a+b
print(c)
print(c.shape)

[[ 0.29902593  2.49533551  1.35709951]
 [ 2.05058485 -0.08294026 -0.72962544]]
(2, 3)


In [8]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [16]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
c = np.random.randn(3,4)
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
        
print(a)
print(b)
print(c)

[[ 0.14493692 -2.45215172 -0.82595302  1.07954215]
 [ 0.62980243 -0.17792951 -0.13380626 -0.25656461]
 [-0.33085595 -1.52885212  0.715218   -1.44958667]]
[[-1.46485038]
 [-0.27427906]
 [ 0.26195903]
 [-0.23663439]]
[[-1.31991345 -2.72643079 -0.56399398  0.84290775]
 [-0.83504795 -0.45220858  0.12815277 -0.493199  ]
 [-1.79570633 -1.80313119  0.97717703 -1.68622107]]


In [18]:
# a.shape = (3,4)
# b.shape = (4,1)

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

# How we can vectorize this? 
c = a + b
c = a.T + b.T
c = a.T + b
c = a + b.T
